### ISSUE TITLE
How to update to 10.1?

### ISSUE THREAD

**Issue by yudhir** [MunGell/openshift-ghost-quickstart#2]
I installed by using this cartidge repo url in the quick start .

**Comment by MunGell** [comment]
Hi @yudhir 

This repository was already updated to 0.10.1

If you are updating from lower versions, just copy `node_modules`, `package.json` and `index.js` from this repository to your repository

**Comment by yudhir** [comment]
Thanks I figured that out. It was easier that i thought.  How can i update the node version because the recommended version is now node 4 and not node 0.10.

**Comment by 23W** [comment]
@yudhir Openshift uses nodejs 0.10.35, so until they does not update it this repository should use same nodejs version.

**Comment by 23W** [comment]
@MunGell Thank you for upgrade to 0.10.1!

**Comment by yudhir** [comment]
@23w no its just a cartidge setting or something.there was a auto updating node package without ghost.

**Comment by 23W** [comment]
@yudhir yes, of course this is a cartridge setting. And OpenShift have another cartridge with auto-updating node to latest version. But: 1. I don't know the good solution how to switch our cartridge to different nodejs version, 2. another OpenShift cartridge (with auto-update) haven't the ghost and it requires to install it manually.

**Comment by MunGell** [comment]
Hi @yudhir @23W 

There are several unofficial cartridges that implement higher version of Node.js on OpenShift platform. I am considering the option to migrate to one of them since OpenShift team don't plan to update their cartridge. For now - 0.10.1 will work with Node 0.10 fine. 

If I will find a way of easy and secure update to higher version of Node - it will be in this repository.

**Comment by 23W** [comment]
@MunGell How about 0.11.0 ? :)

**Comment by 23W** [comment]
@yudhir
Close this issue, please.
